
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import TokenMinterProxyContractArtifactJson from '../../aztec-contracts/token_minter_proxy/target/token_minter_proxy-TokenMinterProxy.json' with { type: 'json' };
export const TokenMinterProxyContractArtifact = loadContractArtifact(TokenMinterProxyContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract TokenMinterProxy;
 */
export class TokenMinterProxyContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, TokenMinterProxyContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): TokenMinterProxyContract {
    return Contract.at(address, TokenMinterProxyContract.artifact, wallet) as TokenMinterProxyContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, ) {
    return new DeployMethod<TokenMinterProxyContract>(PublicKeys.default(), wallet, TokenMinterProxyContractArtifact, (instance, wallet) => TokenMinterProxyContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, ) {
    return new DeployMethod<TokenMinterProxyContract>(publicKeys, wallet, TokenMinterProxyContractArtifact, (instance, wallet) => TokenMinterProxyContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof TokenMinterProxyContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<TokenMinterProxyContract['methods'][M]>
  ) {
    return new DeployMethod<TokenMinterProxyContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      TokenMinterProxyContractArtifact,
      (instance, wallet) => TokenMinterProxyContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return TokenMinterProxyContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(TokenMinterProxyContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'owner' | 'token' | 'can_mint'> {
      return {
        owner: {
      slot: new Fr(1n),
    },
token: {
      slot: new Fr(3n),
    },
can_mint: {
      slot: new Fr(5n),
    }
      } as ContractStorageLayout<'owner' | 'token' | 'can_mint'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** burn_private(user_address: struct, amount: integer, authwit_nonce: field) */
    burn_private: ((user_address: AztecAddressLike, amount: (bigint | number), authwit_nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** burn_public(user_address: struct, amount: integer, authwit_nonce: field) */
    burn_public: ((user_address: AztecAddressLike, amount: (bigint | number), authwit_nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor() */
    constructor: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_owner() */
    get_owner: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_token() */
    get_token: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_minter(minter: struct) */
    is_minter: ((minter: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** mint_to_private(recipient: struct, amount: integer) */
    mint_to_private: ((recipient: AztecAddressLike, amount: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** mint_to_public(recipient: struct, amount: integer) */
    mint_to_public: ((recipient: AztecAddressLike, amount: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_minter(minter: struct, allowed: boolean) */
    set_minter: ((minter: AztecAddressLike, allowed: boolean) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_token(token_address: struct) */
    set_token: ((token_address: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
