
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import TokenBridgeContractArtifactJson from '../../aztec-contracts/token_bridge/target/token_bridge_contract-TokenBridge.json' with { type: 'json' };
export const TokenBridgeContractArtifact = loadContractArtifact(TokenBridgeContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract TokenBridge;
 */
export class TokenBridgeContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, TokenBridgeContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): TokenBridgeContract {
    return Contract.at(address, TokenBridgeContract.artifact, wallet) as TokenBridgeContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, token_minter_proxy: AztecAddressLike, portal: EthAddressLike, human_id_attester_x: FieldLike, human_id_attester_y: FieldLike, circuit_id: FieldLike, action_id: FieldLike, passport_signer_x: FieldLike, passport_signer_y: FieldLike) {
    return new DeployMethod<TokenBridgeContract>(PublicKeys.default(), wallet, TokenBridgeContractArtifact, (instance, wallet) => TokenBridgeContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, token_minter_proxy: AztecAddressLike, portal: EthAddressLike, human_id_attester_x: FieldLike, human_id_attester_y: FieldLike, circuit_id: FieldLike, action_id: FieldLike, passport_signer_x: FieldLike, passport_signer_y: FieldLike) {
    return new DeployMethod<TokenBridgeContract>(publicKeys, wallet, TokenBridgeContractArtifact, (instance, wallet) => TokenBridgeContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof TokenBridgeContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<TokenBridgeContract['methods'][M]>
  ) {
    return new DeployMethod<TokenBridgeContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      TokenBridgeContractArtifact,
      (instance, wallet) => TokenBridgeContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return TokenBridgeContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(TokenBridgeContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'owner' | 'pending_owner' | 'config' | 'human_id_attester_pubkey' | 'clean_hands_circuit_id' | 'clean_hands_action_id' | 'passport_signer_pubkey' | 'clean_hands_nonces' | 'passport_nonces' | 'is_paused'> {
      return {
        owner: {
      slot: new Fr(1n),
    },
pending_owner: {
      slot: new Fr(2n),
    },
config: {
      slot: new Fr(3n),
    },
human_id_attester_pubkey: {
      slot: new Fr(6n),
    },
clean_hands_circuit_id: {
      slot: new Fr(12n),
    },
clean_hands_action_id: {
      slot: new Fr(16n),
    },
passport_signer_pubkey: {
      slot: new Fr(20n),
    },
clean_hands_nonces: {
      slot: new Fr(26n),
    },
passport_nonces: {
      slot: new Fr(27n),
    },
is_paused: {
      slot: new Fr(28n),
    }
      } as ContractStorageLayout<'owner' | 'pending_owner' | 'config' | 'human_id_attester_pubkey' | 'clean_hands_circuit_id' | 'clean_hands_action_id' | 'passport_signer_pubkey' | 'clean_hands_nonces' | 'passport_nonces' | 'is_paused'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** authorize_exit_to_l1_public(recipient: struct, amount: integer, caller_on_l1: struct, authwit_nonce: field, clean_hands: struct, passport: struct) */
    authorize_exit_to_l1_public: ((recipient: EthAddressLike, amount: (bigint | number), caller_on_l1: EthAddressLike, authwit_nonce: FieldLike, clean_hands: { nonce: FieldLike, signature: (bigint | number)[] }, passport: { max_amount: (bigint | number), nonce: FieldLike, deadline: (bigint | number), signature: (bigint | number)[] }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** cancel_ownership_transfer() */
    cancel_ownership_transfer: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** claim_ownership() */
    claim_ownership: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** claim_private(recipient: struct, amount: integer, secret_for_L1_to_L2_message_consumption: field, message_leaf_index: field) */
    claim_private: ((recipient: AztecAddressLike, amount: (bigint | number), secret_for_L1_to_L2_message_consumption: FieldLike, message_leaf_index: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** claim_public(to: struct, amount: integer, secret: field, message_leaf_index: field) */
    claim_public: ((to: AztecAddressLike, amount: (bigint | number), secret: FieldLike, message_leaf_index: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(token_minter_proxy: struct, portal: struct, human_id_attester_x: field, human_id_attester_y: field, circuit_id: field, action_id: field, passport_signer_x: field, passport_signer_y: field) */
    constructor: ((token_minter_proxy: AztecAddressLike, portal: EthAddressLike, human_id_attester_x: FieldLike, human_id_attester_y: FieldLike, circuit_id: FieldLike, action_id: FieldLike, passport_signer_x: FieldLike, passport_signer_y: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** exit_to_l1_private(recipient: struct, amount: integer, caller_on_l1: struct, authwit_nonce: field, clean_hands: struct, passport: struct) */
    exit_to_l1_private: ((recipient: EthAddressLike, amount: (bigint | number), caller_on_l1: EthAddressLike, authwit_nonce: FieldLike, clean_hands: { nonce: FieldLike, signature: (bigint | number)[] }, passport: { max_amount: (bigint | number), nonce: FieldLike, deadline: (bigint | number), signature: (bigint | number)[] }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_config() */
    get_config: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_config_public() */
    get_config_public: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_clean_hands_nonce_used(user: struct, nonce: field) */
    is_clean_hands_nonce_used: ((user: AztecAddressLike, nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_passport_nonce_used(user: struct, nonce: field) */
    is_passport_nonce_used: ((user: AztecAddressLike, nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_paused(paused: boolean) */
    set_paused: ((paused: boolean) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** transfer_ownership(new_owner: struct) */
    transfer_ownership: ((new_owner: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** update_attestation_config(attester_x: field, attester_y: field, circuit_id: field, action_id: field, passport_x: field, passport_y: field) */
    update_attestation_config: ((attester_x: FieldLike, attester_y: FieldLike, circuit_id: FieldLike, action_id: FieldLike, passport_x: FieldLike, passport_y: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
